name = "thongphan-com"
compatibility_date = "2025-01-01"
pages_build_output_dir = "out"

[vars]
DATA_PLATFORM_URL = "https://api.thongphan.com"

# D1 Database binding for Pages Functions
[[d1_databases]]
binding = "DB"
database_name = "thongphan-db"
database_id = "7cffb7f5-c48b-49c2-b215-9611abd734a5"

# KV Namespace binding for Pages Functions
[[kv_namespaces]]
binding = "KV"
id = "18e5b3dde1924e659dd536794f1d2ce2"
preview_id = "e676e1ad29844b24a18fb4c8241b6992"
