// AUTO-GENERATED by scripts/generate-readings-data.mjs
// Run `npm run generate-readings` to regenerate
// DO NOT EDIT MANUALLY

import type { ReadingArticle } from './readings'

export const generatedReadings: ReadingArticle[] = [
  {
    "slug": "bertrand-russell-in-praise-of-idleness",
    "title": "Ca ngợi sự nhàn rỗi",
    "description": "Phản biện đạo đức tôn sùng lao động và bảo vệ nhàn rỗi như điều kiện của văn minh.",
    "author": "Bertrand Russell",
    "source": "Harper's Magazine",
    "sourceUrl": "https://harpers.org/archive/1932/10/in-praise-of-idleness/",
    "sourcePublishedAt": null,
    "translator": null,
    "editor": null,
    "translatedAt": null,
    "lastReviewedAt": "2026-07-10",
    "rightsStatus": "source-link-only",
    "minutes": 35,
    "topics": [
      "ton-giao",
      "he-gia-tri"
    ],
    "intent": "clarity",
    "durationBand": "over-20",
    "readingPath": "/library/read/bertrand-russell-in-praise-of-idleness",
    "coreIdea": "Phản biện đạo đức tôn sùng lao động và bảo vệ nhàn rỗi như điều kiện của văn minh.",
    "whyRead": "Nội dung này tạo một khe nứt trong cách nhìn quen thuộc và buộc người đọc kiểm tra lại điều mình xem là hiển nhiên.",
    "reflection": "Điều gì ở đây là dữ kiện, điều gì chỉ là câu chuyện diễn giải?",
    "authorProfile": {
      "title": "Bertrand Russell là ai?",
      "summary": "Bertrand Russell là triết gia, nhà logic học, nhà hoạt động xã hội người Anh và một trong những trí thức công chúng quan trọng nhất thế kỷ 20.",
      "bullets": [
        "Đồng tác giả Principia Mathematica, một công trình nền tảng của logic hiện đại, và đoạt Nobel Văn học năm 1950.",
        "Là một trong những gương mặt lớn của triết học phân tích, đồng thời là trí thức công chúng viết nhiều về giáo dục, chiến tranh, tự do và đời sống tốt đẹp.",
        "In Praise of Idleness phản biện đạo đức tôn sùng lao động, đặt nhàn rỗi như điều kiện của văn minh."
      ]
    },
    "contentContext": {
      "title": "Bài này ra đời trong bối cảnh nào?",
      "summary": "Bertrand Russell viết bài luận này năm 1932, giữa bối cảnh công nghiệp hóa, thất nghiệp và đạo đức lao động đang được xem như điều hiển nhiên.",
      "bullets": [
        "Bài đặt lại câu hỏi: lao động là phương tiện hay mục đích của đời sống?",
        "Nó rất hợp với định vị rèn Taste vì buộc người đọc phân biệt đạo đức thật với thói quen xã hội được thần thánh hóa."
      ]
    },
    "contentChecksum": "sha256:bfdcbdb78a745da8d44c7bc584c8633cc4c92064daea16b52ce68d6b35d0f617",
    "contentVersion": 1,
    "publicationMode": "summary",
    "images": [],
    "audio": []
  },
  {
    "slug": "chimamanda-ngozi-adichie-the-danger-of-a-single-story",
    "title": "Sự nguy hiểm của một câu chuyện duy nhất",
    "description": "Một câu chuyện duy nhất có thể làm phẳng con người, nơi chốn và văn hóa; nhiều câu chuyện hơn là điều kiện để nhìn người khác có phẩm giá và chiều sâu.",
    "author": "Chimamanda Ngozi Adichie",
    "source": "TED",
    "sourceUrl": "https://www.ted.com/talks/chimamanda_ngozi_adichie_the_danger_of_a_single_story",
    "sourcePublishedAt": null,
    "translator": null,
    "editor": null,
    "translatedAt": null,
    "lastReviewedAt": "2026-07-10",
    "rightsStatus": "source-link-only",
    "minutes": 18,
    "topics": [
      "truyen-thong",
      "khung-nhin"
    ],
    "intent": "clarity",
    "durationBand": "10-20",
    "readingPath": "/library/read/chimamanda-ngozi-adichie-the-danger-of-a-single-story",
    "coreIdea": "Một câu chuyện duy nhất có thể làm phẳng con người, nơi chốn và văn hóa; nhiều câu chuyện hơn là điều kiện để nhìn người khác có phẩm giá và chiều sâu.",
    "whyRead": "Bài này rèn gu thẩm định câu chuyện: biết hỏi ai đang kể, kể từ đâu, bỏ qua điều gì và quyền lực nào khiến một phiên bản trở thành sự thật cuối cùng trong đầu người nghe.",
    "reflection": "Mình đang nhìn ai, nhóm nào hoặc nơi nào bằng một câu chuyện duy nhất?",
    "authorProfile": {
      "title": "Chimamanda Ngozi Adichie là ai?",
      "summary": "Chimamanda Ngozi Adichie là nhà văn Nigeria, một trong những tiếng nói văn chương và diễn thuyết có ảnh hưởng lớn về căn tính, giới, hậu thuộc địa và quyền lực của câu chuyện.",
      "bullets": [
        "Tác giả của Purple Hibiscus, Half of a Yellow Sun và Americanah; Half of a Yellow Sun thắng Orange Prize, Americanah thắng National Book Critics Circle Award.",
        "Nhận MacArthur Fellowship năm 2008; tác phẩm của bà được dịch ra hơn 30 ngôn ngữ.",
        "Bài TED The Danger of a Single Story năm 2009 là một trong những bài nói phổ biến nhất của TED về truyền thông, căn tính và định kiến."
      ]
    },
    "contentContext": {
      "title": "Bài nói này ra đời trong bối cảnh nào?",
      "summary": "Bài nói được trình bày tại TEDGlobal 2009, trong bối cảnh các cuộc đối thoại toàn cầu về văn hóa, truyền thông và quyền đại diện đang trở nên nổi bật hơn.",
      "bullets": [
        "Adichie dùng chính trải nghiệm đọc, viết và sống giữa Nigeria - Hoa Kỳ để cho thấy cách câu chuyện định hình nhận thức.",
        "Bài nói không phủ nhận những câu chuyện tiêu cực, mà phản đối việc biến chúng thành câu chuyện duy nhất.",
        "Nó đặc biệt phù hợp với thư viện này vì rèn năng lực nhìn nhiều lớp trước khi đánh giá một con người, cộng đồng hay nền văn hóa."
      ]
    },
    "contentChecksum": "sha256:3caed1f9021416ac8722d86ca7774935382ab8ddd93fcfaa30196b8c697aff38",
    "contentVersion": 1,
    "publicationMode": "summary",
    "images": [],
    "audio": []
  },
  {
    "slug": "david-deutsch-a-new-way-to-explain-explanation",
    "title": "Giải thích tốt là thứ khó bị thay đổi tùy tiện",
    "description": "Giải thích tốt không chỉ khớp dữ kiện mà còn khó bị biến đổi tùy tiện mà vẫn giữ sức giải thích.",
    "author": "David Deutsch",
    "source": "TED",
    "sourceUrl": "https://www.ted.com/talks/david_deutsch_a_new_way_to_explain_explanation",
    "sourcePublishedAt": null,
    "translator": null,
    "editor": null,
    "translatedAt": null,
    "lastReviewedAt": "2026-07-10",
    "rightsStatus": "source-link-only",
    "minutes": 16,
    "topics": [
      "worldview",
      "reframing",
      "pluralism"
    ],
    "intent": "clarity",
    "durationBand": "10-20",
    "readingPath": "/library/read/david-deutsch-a-new-way-to-explain-explanation",
    "coreIdea": "Giải thích tốt không chỉ khớp dữ kiện mà còn khó bị biến đổi tùy tiện mà vẫn giữ sức giải thích.",
    "whyRead": "Nội dung này tạo một khe nứt trong cách nhìn quen thuộc và buộc người đọc kiểm tra lại điều mình xem là hiển nhiên.",
    "reflection": "Một người ở nền văn hóa khác sẽ đọc vấn đề này khác anh ở điểm nào?",
    "authorProfile": {
      "title": "David Deutsch là ai?",
      "summary": "David Deutsch là nhà vật lý tại University of Oxford, một trong những người đặt nền móng cho tính toán lượng tử và là tác giả có ảnh hưởng trong triết học khoa học.",
      "bullets": [
        "Được xem là một trong những người khai sinh lý thuyết tính toán lượng tử và là Fellow of the Royal Society.",
        "Tác giả The Fabric of Reality và The Beginning of Infinity, hai cuốn sách nối vật lý, tri thức luận, tiến hóa, tính toán và văn minh nhân loại.",
        "Bài nói này cô đọng tiêu chuẩn của một lời giải thích tốt: không dễ bị biến đổi tùy tiện mà vẫn giữ sức giải thích."
      ]
    },
    "contentContext": {
      "title": "Bối cảnh bài viết này là gì?",
      "summary": "Bài TED này được trình bày năm 2009, trong mạch các bài nói về khoa học, tri thức và cách con người tạo ra giải thích để hiểu thế giới không nhìn thấy.",
      "bullets": [
        "Nó phù hợp với thư viện vì giúp người đọc nâng tiêu chuẩn thẩm định ý tưởng.",
        "Trọng tâm không phải biết nhiều dữ kiện hơn, mà là phân biệt lời giải thích bền với câu chuyện có thể sửa tùy tiện."
      ]
    },
    "contentChecksum": "sha256:e882ee93e73243941cac70498e100259768b34e6c3bd683a0cb9f069442266eb",
    "contentVersion": 1,
    "publicationMode": "summary",
    "images": [],
    "audio": []
  },
  {
    "slug": "derek-sivers-projecting-meaning",
    "title": "Gán ý nghĩa",
    "description": "Ý nghĩa không phải lúc nào cũng nằm sẵn trong sự vật; rất nhiều khi chính ta là người gán ý nghĩa, rồi sống như thể ý nghĩa đó là thật.",
    "author": "Derek Sivers",
    "source": "Derek Sivers",
    "sourceUrl": "https://sive.rs/meaning",
    "sourcePublishedAt": null,
    "translator": null,
    "editor": null,
    "translatedAt": null,
    "lastReviewedAt": "2026-07-10",
    "rightsStatus": "source-link-only",
    "minutes": 8,
    "topics": [
      "worldview",
      "reframing",
      "pluralism"
    ],
    "intent": "clarity",
    "durationBand": "under-10",
    "readingPath": "/library/read/derek-sivers-projecting-meaning",
    "coreIdea": "Ý nghĩa không phải lúc nào cũng nằm sẵn trong sự vật; rất nhiều khi chính ta là người gán ý nghĩa, rồi sống như thể ý nghĩa đó là thật.",
    "whyRead": "Bài ngắn này rèn một năng lực rất quan trọng của Taste: biết phân biệt giữa điều đang xảy ra và câu chuyện mình đang đặt lên điều đó.",
    "reflection": "Mình đang gán ý nghĩa nào lên một việc vốn chỉ đang là chính nó?",
    "authorProfile": {
      "title": "Derek Sivers là ai?",
      "summary": "Derek Sivers là doanh nhân, nhạc sĩ, lập trình viên và tác giả nổi tiếng với lối viết ngắn, sắc và thực dụng về đời sống, lựa chọn và tư duy độc lập.",
      "bullets": [
        "Sáng lập CD Baby, một trong những nền tảng quan trọng giúp nhạc sĩ độc lập bán nhạc trực tuyến, sau đó bán công ty và dành phần lớn tiền cho quỹ từ thiện.",
        "Tác giả Anything You Want, Hell Yeah or No, How to Live và Useful Not True.",
        "Văn của Sivers thường không cố thuyết phục bằng độ dài, mà bằng một cú xoay góc nhìn rất gọn."
      ]
    },
    "contentContext": {
      "title": "Bài này ra đời trong bối cảnh nào?",
      "summary": "Bài được Derek Sivers đăng ngày 23/06/2011 trên website cá nhân, trong mạch các ghi chú ngắn về cách con người tạo ra câu chuyện để hiểu đời sống.",
      "bullets": [
        "Sivers bắt đầu từ việc học chữ Hán và những câu chuyện ông tự tưởng tượng phía sau từng chữ.",
        "Sau đó bài chuyển sang Talking Heads, sự ngẫu nhiên trong ca từ và cách người nghe tự tạo kết nối.",
        "Điểm đáng giữ là câu hỏi: nếu ý nghĩa do mình đặt vào, mình có thể lấy một ý nghĩa đang làm mình khổ ra khỏi sự việc không?"
      ]
    },
    "contentChecksum": "sha256:254cd3776839075ec17ee08b08e459c4c572caecbcd6a66807ade8b46a46773b",
    "contentVersion": 1,
    "publicationMode": "summary",
    "images": [],
    "audio": []
  },
  {
    "slug": "george-orwell-politics-and-the-english-language",
    "title": "Ngôn ngữ mục ruỗng làm tư duy mục ruỗng",
    "description": "Ngôn ngữ mơ hồ vừa là sản phẩm vừa là công cụ của tư duy chính trị cẩu thả.",
    "author": "George Orwell",
    "source": "The Orwell Foundation",
    "sourceUrl": "https://www.orwellfoundation.com/the-orwell-foundation/orwell/essays-and-other-works/politics-and-the-english-language/",
    "sourcePublishedAt": null,
    "translator": null,
    "editor": null,
    "translatedAt": null,
    "lastReviewedAt": "2026-07-10",
    "rightsStatus": "source-link-only",
    "minutes": 30,
    "topics": [
      "worldview",
      "reframing",
      "pluralism"
    ],
    "intent": "clarity",
    "durationBand": "over-20",
    "readingPath": "/library/read/george-orwell-politics-and-the-english-language",
    "coreIdea": "Ngôn ngữ mơ hồ vừa là sản phẩm vừa là công cụ của tư duy chính trị cẩu thả.",
    "whyRead": "Nội dung này tạo một khe nứt trong cách nhìn quen thuộc và buộc người đọc kiểm tra lại điều mình xem là hiển nhiên.",
    "reflection": "Nếu tin ngược lại, anh sẽ nhìn thế giới khác đi ra sao?",
    "authorProfile": {
      "title": "George Orwell là ai?",
      "summary": "George Orwell là nhà văn, nhà báo và nhà phê bình chính trị người Anh, nổi tiếng với Animal Farm, Nineteen Eighty-Four và các bài luận về quyền lực, ngôn ngữ, tự do.",
      "bullets": [
        "Animal Farm và Nineteen Eighty-Four trở thành hai tác phẩm kinh điển toàn cầu về tuyên truyền, toàn trị và kiểm soát tư duy.",
        "Từng trải qua đời sống thuộc địa, nghèo đói và chiến tranh; những trải nghiệm đó đi vào Homage to Catalonia, The Road to Wigan Pier và nhiều bài luận chính trị.",
        "Văn của Orwell nổi bật bởi sự trong sáng, nghi ngờ quyền lực và chống lại ngôn ngữ che đậy sự thật.",
        "Politics and the English Language là một chuẩn mực để rèn gu viết rõ, nghĩ rõ và đọc chính trị tỉnh táo hơn."
      ]
    },
    "contentContext": {
      "title": "Bài này ra đời trong bối cảnh nào?",
      "summary": "Bài luận xuất hiện trên Horizon năm 1946, ngay sau Thế chiến II, khi Orwell quan sát cách chính trị hiện đại làm mục ruỗng ngôn ngữ.",
      "bullets": [
        "Orwell không chỉ dạy viết tốt hơn, mà chỉ ra quan hệ giữa câu chữ, tư duy và quyền lực.",
        "Bài này nên được đọc như một công cụ vệ sinh trí óc trước mọi diễn ngôn chính trị."
      ]
    },
    "contentChecksum": "sha256:f24ff95cf605f9e4e5263e2fe56e6a77f053154ff54f08e3bc250d36df818568",
    "contentVersion": 1,
    "publicationMode": "summary",
    "images": [],
    "audio": []
  },
  {
    "slug": "hans-rosling-the-best-stats-you-have-ever-seen",
    "title": "Những thống kê hay nhất bạn từng thấy",
    "description": "Thế giới không còn chia gọn thành “phương Tây” và “thế giới thứ ba”; dữ liệu động, chi tiết và dễ nhìn giúp ta sửa những mô hình thế giới đã lỗi thời.",
    "author": "Hans Rosling",
    "source": "TED",
    "sourceUrl": "https://www.ted.com/talks/hans_rosling_the_best_stats_you_ve_ever_seen",
    "sourcePublishedAt": null,
    "translator": null,
    "editor": null,
    "translatedAt": null,
    "lastReviewedAt": "2026-07-10",
    "rightsStatus": "source-link-only",
    "minutes": 20,
    "topics": [
      "worldview",
      "data",
      "global-development"
    ],
    "intent": "clarity",
    "durationBand": "10-20",
    "readingPath": "/library/read/hans-rosling-the-best-stats-you-have-ever-seen",
    "coreIdea": "Thế giới không còn chia gọn thành “phương Tây” và “thế giới thứ ba”; dữ liệu động, chi tiết và dễ nhìn giúp ta sửa những mô hình thế giới đã lỗi thời.",
    "whyRead": "Bài này rèn năng lực dùng dữ liệu để phá định kiến: không chỉ tin vào cảm giác chung, mà học cách nhìn chuyển động, phân phối và khác biệt bên trong từng nhóm.",
    "reflection": "Mô hình thế giới nào trong đầu mình có thể đã quá cũ vì thiếu dữ liệu chuyển động?",
    "authorProfile": {
      "title": "Hans Rosling là ai?",
      "summary": "Hans Rosling (1948-2017) là bác sĩ, giáo sư sức khỏe toàn cầu người Thụy Điển, đồng sáng lập Gapminder và một trong những nhà truyền thông dữ liệu có ảnh hưởng nhất thế giới.",
      "bullets": [
        "Giáo sư sức khỏe toàn cầu tại Karolinska Institute, chuyên dùng dữ liệu để sửa những ngộ nhận về phát triển, dân số và y tế.",
        "Đồng sáng lập Gapminder năm 2005 cùng Ola Rosling và Anna Rosling Rönnlund để biến dữ liệu toàn cầu thành tri thức công chúng.",
        "Bài TED 2006 The Best Stats You've Ever Seen trở thành một trong những bài TED được xem nhiều nhất và định hình cách trình bày dữ liệu hiện đại."
      ]
    },
    "contentContext": {
      "title": "Bài nói này ra đời trong bối cảnh nào?",
      "summary": "Đây là bài TED năm 2006, nơi Rosling dùng phần mềm dữ liệu động của Gapminder để phản biện cách nhìn cũ về “phương Tây” và “thế giới thứ ba”.",
      "bullets": [
        "Bài nói xuất hiện đúng lúc dữ liệu công đã nhiều hơn, nhưng vẫn khó tiếp cận và khó hiểu với công chúng.",
        "Rosling dùng biểu đồ bong bóng chuyển động để cho thấy quốc gia, khu vực và nhóm thu nhập thay đổi theo thời gian.",
        "Nó quan trọng với thư viện vì dạy người đọc không chỉ đọc kết luận, mà đọc cấu trúc dữ liệu phía sau kết luận."
      ]
    },
    "contentChecksum": "sha256:eaea966d3f3a5434373ebf4ac3dc987950506ff01a7f5fb8ac584d1d55b6170a",
    "contentVersion": 1,
    "publicationMode": "summary",
    "images": [],
    "audio": []
  },
  {
    "slug": "jonathan-haidt-the-moral-roots-of-liberals-and-conservatives",
    "title": "Gốc rễ đạo đức của tự do và bảo thủ",
    "description": "Các nền tảng đạo đức khác nhau khiến người tử tế vẫn bất đồng sâu sắc; muốn hiểu xã hội phải bước ra khỏi ma trận đạo đức của phe mình.",
    "author": "Jonathan Haidt",
    "source": "TED",
    "sourceUrl": "https://www.ted.com/talks/jonathan_haidt_the_moral_roots_of_liberals_and_conservatives",
    "sourcePublishedAt": null,
    "translator": null,
    "editor": null,
    "translatedAt": null,
    "lastReviewedAt": "2026-07-10",
    "rightsStatus": "source-link-only",
    "minutes": 18,
    "topics": [
      "dao-duc",
      "chinh-tri",
      "khiem-nhuong"
    ],
    "intent": "taste",
    "durationBand": "10-20",
    "readingPath": "/library/read/jonathan-haidt-the-moral-roots-of-liberals-and-conservatives",
    "coreIdea": "Các nền tảng đạo đức khác nhau khiến người tử tế vẫn bất đồng sâu sắc; muốn hiểu xã hội phải bước ra khỏi ma trận đạo đức của phe mình.",
    "whyRead": "Bài này rèn gu phán đoán trong thời đại phân cực: thay vì hỏi phe nào ngu hoặc xấu, người đọc học cách nhận ra hệ giá trị nào đang vận hành phía sau một lập trường.",
    "reflection": "Khi bất đồng với ai đó, mình đang nhìn họ bằng hệ đạo đức hai kênh hay năm kênh?",
    "authorProfile": {
      "title": "Jonathan Haidt là ai?",
      "summary": "Jonathan Haidt là nhà tâm lý học xã hội người Mỹ, giáo sư tại NYU Stern, nổi tiếng với nghiên cứu về đạo đức, cảm xúc, chính trị và sự phân cực văn hóa.",
      "bullets": [
        "Tác giả The Righteous Mind, The Coddling of the American Mind và The Anxious Generation, các cuốn sách có ảnh hưởng lớn về đạo đức, tự do học thuật, công nghệ và sức khỏe tinh thần.",
        "Giữ vị trí Thomas Cooley Professor of Ethical Leadership tại NYU Stern School of Business.",
        "Công trình moral foundations của ông giúp người đọc hiểu vì sao người tử tế vẫn có thể bất đồng sâu sắc về các vấn đề đạo đức và chính trị."
      ]
    },
    "contentContext": {
      "title": "Bài nói này ra đời trong bối cảnh nào?",
      "summary": "Bài TED này được trình bày trong bối cảnh sau các cuộc bầu cử Mỹ đầu thập niên 2000, khi phân cực chính trị và định kiến phe nhóm trở thành một vấn đề nổi bật.",
      "bullets": [
        "Haidt nói trước một khán phòng TED có khuynh hướng tự do, nên bài nói cũng là một lời mời tự soi lại phe của chính người nghe.",
        "Bài nói giới thiệu cách hiểu đạo đức như một bộ chỉnh âm nhiều kênh, thay vì một thước đo đúng sai duy nhất.",
        "Điểm đáng đọc là nó biến bất đồng chính trị thành bài học về gu phán đoán và khiêm nhường đạo đức."
      ]
    },
    "contentChecksum": "sha256:e42f769e8e42f760d124b0bdf8db946c543e58bb9ff2a73851c1d56cb425c2a3",
    "contentVersion": 1,
    "publicationMode": "summary",
    "images": [],
    "audio": []
  },
  {
    "slug": "julia-galef-why-you-think-youre-right-even-if-youre-wrong",
    "title": "Vì sao bạn nghĩ mình đúng, ngay cả khi bạn sai",
    "description": "Phán đoán tốt không chỉ đến từ IQ hay kiến thức, mà từ động cơ cảm xúc: ta muốn bảo vệ niềm tin, hay muốn nhìn thế giới rõ nhất có thể.",
    "author": "Julia Galef",
    "source": "TED",
    "sourceUrl": "https://www.ted.com/talks/julia_galef_why_you_think_you_re_right_even_if_you_re_wrong",
    "sourcePublishedAt": null,
    "translator": null,
    "editor": null,
    "translatedAt": null,
    "lastReviewedAt": "2026-07-10",
    "rightsStatus": "source-link-only",
    "minutes": 12,
    "topics": [
      "phan-doan",
      "thien-kien",
      "scout-mindset"
    ],
    "intent": "taste",
    "durationBand": "10-20",
    "readingPath": "/library/read/julia-galef-why-you-think-youre-right-even-if-youre-wrong",
    "coreIdea": "Phán đoán tốt không chỉ đến từ IQ hay kiến thức, mà từ động cơ cảm xúc: ta muốn bảo vệ niềm tin, hay muốn nhìn thế giới rõ nhất có thể.",
    "whyRead": "Bài này rèn gu thẩm định trong thời đại AI vì nó chạm vào lỗi nền của người đọc: dùng trí thông minh để thắng tranh luận thay vì để thấy sự thật rõ hơn.",
    "reflection": "Lần gần nhất mình bảo vệ một niềm tin như người lính là khi nào? Nếu đổi sang tư duy người trinh sát, mình sẽ hỏi câu gì khác?",
    "authorProfile": {
      "title": "Julia Galef là ai?",
      "summary": "Julia Galef là tác giả, diễn giả và người phổ biến tư duy duy lý, nổi tiếng với khái niệm scout mindset - tư duy người trinh sát.",
      "bullets": [
        "Tác giả The Scout Mindset, cuốn sách bàn về cách nhìn sự thật rõ hơn thay vì bảo vệ niềm tin hiện có.",
        "Đồng sáng lập Center for Applied Rationality và từng dẫn Rationally Speaking, một podcast phổ biến về khoa học, triết học và tư duy duy lý.",
        "Bài TED 2016 của cô đưa cặp khái niệm soldier mindset và scout mindset đến công chúng rộng hơn."
      ]
    },
    "contentContext": {
      "title": "Bài nói này ra đời trong bối cảnh nào?",
      "summary": "Bài TED này dùng vụ Dreyfus ở Pháp thế kỷ 19 để minh họa lý luận có động cơ và cách một người có thể vượt qua thiên kiến phe mình để bảo vệ sự thật.",
      "bullets": [
        "Galef đối chiếu hai trạng thái tâm trí: người lính muốn bảo vệ phe mình, người trinh sát muốn biết địa hình thật sự ra sao.",
        "Bài nói đặc biệt phù hợp với người viết và người làm tri thức vì nó tách sự thông minh khỏi khả năng nhìn đúng.",
        "Câu hỏi cuối của bài biến tư duy phản biện thành một câu hỏi về khao khát: mình muốn đúng, hay muốn thấy rõ?"
      ]
    },
    "contentChecksum": "sha256:83712777e8de1fac46f4d5b0df311a14d73ac1aa1884a738dd66cdba8ab22eab",
    "contentVersion": 1,
    "publicationMode": "summary",
    "images": [],
    "audio": []
  },
  {
    "slug": "paul-graham-copy-what-you-like",
    "title": "Bắt chước thứ mình thật sự thích",
    "description": "Bắt chước không xấu; cái nguy hiểm là bắt chước thứ mình chỉ thấy ấn tượng, thay vì thứ mình thật sự thích.",
    "author": "Paul Graham",
    "source": "Paul Graham",
    "sourceUrl": "https://paulgraham.com/copy.html",
    "sourcePublishedAt": null,
    "translator": null,
    "editor": null,
    "translatedAt": null,
    "lastReviewedAt": "2026-07-10",
    "rightsStatus": "source-link-only",
    "minutes": 10,
    "topics": [
      "sang-tao",
      "nghe-thuat",
      "giong-rieng"
    ],
    "intent": "taste",
    "durationBand": "10-20",
    "readingPath": "/library/read/paul-graham-copy-what-you-like",
    "coreIdea": "Bắt chước không xấu; cái nguy hiểm là bắt chước thứ mình chỉ thấy ấn tượng, thay vì thứ mình thật sự thích.",
    "whyRead": "Bài này rất hợp với định vị rèn gu cá nhân: muốn có giọng riêng, trước hết phải biết tiêu chuẩn nào trong mình là thật, tiêu chuẩn nào chỉ là sự phục tùng thẩm quyền.",
    "reflection": "Mình đang bắt chước điều mình thật sự thích, hay điều mình nghĩ là mình nên thích để trông có gu?",
    "authorProfile": {
      "title": "Paul Graham là ai?",
      "summary": "Paul Graham là lập trình viên, nhà đầu tư, đồng sáng lập Y Combinator và một trong những cây bút essay có ảnh hưởng nhất trong giới startup và công nghệ.",
      "bullets": [
        "Đồng sáng lập Y Combinator năm 2005 cùng Jessica Livingston, Robert Morris và Trevor Blackwell; YC đã định hình mô hình startup accelerator hiện đại.",
        "Trước đó ông đồng sáng lập Viaweb, một trong những công ty phần mềm dạng dịch vụ đầu tiên, bán cho Yahoo và trở thành Yahoo Store.",
        "Các essay trên paulgraham.com trở thành tài liệu nền của nhiều thế hệ founder nhờ cách kết hợp lập trình, startup, lịch sử và tư duy độc lập."
      ]
    },
    "contentContext": {
      "title": "Bài này ra đời trong bối cảnh nào?",
      "summary": "Paul Graham viết bài này vào tháng 7/2006, trong mạch các essay về taste, nghệ thuật, lập trình và cách một người tìm ra tiêu chuẩn chất lượng của riêng mình.",
      "bullets": [
        "Bài không cổ vũ sao chép bề mặt; nó phân biệt giữa bắt chước điều tốt thật và bắt chước thứ chỉ có uy tín xã hội.",
        "Graham đi qua viết văn, triết học, hệ chuyên gia và hội họa để chỉ ra một lỗi chung: nhầm sự ngưỡng mộ với gu thật.",
        "Điểm đáng giữ là câu cuối: trong chuyện chất lượng, anh phải tự mình tìm ra điều gì là tốt."
      ]
    },
    "contentChecksum": "sha256:66a2e1ff58035a7299b62bcc5775adabbb4205a4aab6c778ec90132d4864e1a5",
    "contentVersion": 1,
    "publicationMode": "summary",
    "images": [],
    "audio": []
  },
  {
    "slug": "paul-graham-what-you-cant-say",
    "title": "Điều gì bạn không thể nói?",
    "description": "Cách phát hiện những điều cấm kỵ của thời đại bằng việc tìm xem điều gì không thể nói ra.",
    "author": "Paul Graham",
    "source": "Paul Graham",
    "sourceUrl": "https://paulgraham.com/say.html",
    "sourcePublishedAt": null,
    "translator": null,
    "editor": null,
    "translatedAt": null,
    "lastReviewedAt": "2026-07-10",
    "rightsStatus": "source-link-only",
    "minutes": 18,
    "topics": [
      "worldview",
      "reframing",
      "pluralism"
    ],
    "intent": "clarity",
    "durationBand": "10-20",
    "readingPath": "/library/read/paul-graham-what-you-cant-say",
    "coreIdea": "Cách phát hiện những điều cấm kỵ của thời đại bằng việc tìm xem điều gì không thể nói ra.",
    "whyRead": "Nội dung này tạo một khe nứt trong cách nhìn quen thuộc và buộc người đọc kiểm tra lại điều mình xem là hiển nhiên.",
    "reflection": "Khung mặc định nào trong đầu anh bị nội dung này làm lung lay?",
    "authorProfile": {
      "title": "Paul Graham là ai?",
      "summary": "Paul Graham là lập trình viên, nhà đầu tư, đồng sáng lập Y Combinator và một trong những cây bút essay có ảnh hưởng nhất trong giới startup và công nghệ.",
      "bullets": [
        "Đồng sáng lập Y Combinator năm 2005 cùng Jessica Livingston, Robert Morris và Trevor Blackwell; YC đã định hình mô hình startup accelerator hiện đại.",
        "Trước đó ông đồng sáng lập Viaweb, một trong những công ty phần mềm dạng dịch vụ đầu tiên, bán cho Yahoo và trở thành Yahoo Store.",
        "Các essay trên paulgraham.com trở thành tài liệu nền của nhiều thế hệ founder nhờ cách kết hợp lập trình, startup, lịch sử và tư duy độc lập.",
        "What You Can't Say là một bài tập rèn năng lực phát hiện điều cấm kỵ của thời đại."
      ]
    },
    "contentContext": {
      "title": "Bài này ra đời trong bối cảnh nào?",
      "summary": "Paul Graham viết bài này vào tháng 1/2004, trước thời mạng xã hội đại chúng, nhưng câu hỏi về điều không thể nói ngày càng quan trọng trong thời đại AI và đám đông số.",
      "bullets": [
        "Bài không cổ vũ nói bừa; nó rèn khả năng tách suy nghĩ riêng khỏi thời trang đạo đức của thời đại.",
        "Điểm đáng giữ là năng lực nhìn ra vùng cấm trong tư duy trước khi biến nó thành lập trường công khai."
      ]
    },
    "contentChecksum": "sha256:2a36f9f3aad73ab7a197ec853039bc0919552a8012bb177b670d5d1eb4668a31",
    "contentVersion": 1,
    "publicationMode": "summary",
    "images": [],
    "audio": []
  },
  {
    "slug": "richard-feynman-cargo-cult-science",
    "title": "Đừng tự lừa mình",
    "description": "Tính liêm chính khoa học đòi hỏi chủ động nêu các dữ kiện có thể khiến chính mình sai.",
    "author": "Richard Feynman",
    "source": "Caltech",
    "sourceUrl": "https://calteches.library.caltech.edu/51/2/CargoCult.htm",
    "sourcePublishedAt": null,
    "translator": null,
    "editor": null,
    "translatedAt": null,
    "lastReviewedAt": "2026-07-10",
    "rightsStatus": "source-link-only",
    "minutes": 25,
    "topics": [
      "worldview",
      "reframing",
      "pluralism"
    ],
    "intent": "clarity",
    "durationBand": "over-20",
    "readingPath": "/library/read/richard-feynman-cargo-cult-science",
    "coreIdea": "Tính liêm chính khoa học đòi hỏi chủ động nêu các dữ kiện có thể khiến chính mình sai.",
    "whyRead": "Nội dung này tạo một khe nứt trong cách nhìn quen thuộc và buộc người đọc kiểm tra lại điều mình xem là hiển nhiên.",
    "reflection": "Điều gì ở đây là dữ kiện, điều gì chỉ là câu chuyện diễn giải?",
    "authorProfile": {
      "title": "Richard Feynman là ai?",
      "summary": "Richard Feynman là nhà vật lý lý thuyết người Mỹ, đoạt Nobel Vật lý năm 1965 và nổi tiếng vì khả năng giải thích khoa học sắc bén, trực diện.",
      "bullets": [
        "Nhận Nobel Vật lý cho công trình về điện động lực học lượng tử (QED), một nền tảng của vật lý hiện đại.",
        "Được nhớ đến qua Feynman Lectures on Physics, các sơ đồ Feynman và tinh thần tò mò cực kỳ thực nghiệm.",
        "Cargo Cult Science là bài nói kinh điển về chính trực khoa học và nguy cơ tự lừa mình."
      ]
    },
    "contentContext": {
      "title": "Bài này ra đời trong bối cảnh nào?",
      "summary": "Đây là bài phát biểu tốt nghiệp tại Caltech năm 1974, nơi Feynman nói với sinh viên khoa học về chính trực trí tuệ trước khi bước vào đời nghề nghiệp.",
      "bullets": [
        "Bối cảnh tốt nghiệp khiến bài nói có sắc thái di chúc nghề nghiệp hơn là bài giảng kỹ thuật.",
        "Bài này đặc biệt quan trọng với người muốn có gu đánh giá: biết nghi ngờ cả điều mình muốn tin."
      ]
    },
    "contentChecksum": "sha256:03485a7171e9da35aaff129fd4ff8d397875ab20fe73e2cc3abf6c02ea71333b",
    "contentVersion": 1,
    "publicationMode": "summary",
    "images": [],
    "audio": []
  },
  {
    "slug": "steve-jobs-2005-stanford-commencement-address",
    "title": "Hãy tìm điều bạn yêu",
    "description": "Ba câu chuyện về kết nối những dấu chấm, tình yêu và mất mát, cùng cái chết như bộ lọc cho những lựa chọn quan trọng.",
    "author": "Steve Jobs",
    "source": "Stanford University",
    "sourceUrl": "https://news.stanford.edu/stories/2005/06/youve-got-find-love-jobs-says",
    "sourcePublishedAt": null,
    "translator": null,
    "editor": null,
    "translatedAt": null,
    "lastReviewedAt": "2026-07-10",
    "rightsStatus": "source-link-only",
    "minutes": 24,
    "topics": [
      "taste",
      "work",
      "mortality"
    ],
    "intent": "taste",
    "durationBand": "over-20",
    "readingPath": "/library/read/steve-jobs-2005-stanford-commencement-address",
    "coreIdea": "Ba câu chuyện về kết nối những dấu chấm, tình yêu và mất mát, cùng cái chết như bộ lọc cho những lựa chọn quan trọng.",
    "whyRead": "Một bài mở đầu tốt cho thư viện vì nó dạy người đọc nhìn lại đời mình bằng tiêu chuẩn của sự tò mò, tình yêu công việc và ý thức về thời gian hữu hạn.",
    "reflection": "Nếu nhìn lại từ tương lai, những dấu chấm nào trong đời bạn có thể đang chờ được kết nối?",
    "authorProfile": {
      "title": "Steve Jobs là ai?",
      "summary": "Steve Jobs (1955-2011) là doanh nhân, nhà sáng lập Apple và một trong những nhân vật có ảnh hưởng lớn nhất tới công nghệ tiêu dùng hiện đại.",
      "bullets": [
        "Đồng sáng lập Apple năm 1976, sau đó dẫn dắt sự ra đời của Macintosh, iMac, iPod, iPhone và iPad.",
        "Sáng lập NeXT và góp phần đưa Pixar trở thành hãng phim hoạt hình máy tính có ảnh hưởng toàn cầu.",
        "Được nhớ đến bởi khả năng kết hợp công nghệ, thiết kế, trải nghiệm người dùng và kể chuyện sản phẩm."
      ]
    },
    "contentContext": {
      "title": "Bài nói này ra đời trong bối cảnh nào?",
      "summary": "Đây là bài phát biểu của Steve Jobs tại lễ tốt nghiệp Stanford University ngày 12/06/2005, sáu năm trước khi ông qua đời.",
      "bullets": [
        "Ông không giảng một bài lý thuyết về thành công, mà kể ba câu chuyện cá nhân: kết nối những dấu chấm, tình yêu và mất mát, cái chết.",
        "Thời điểm đó Jobs đã trở lại Apple, Pixar đang ở đỉnh cao, và iPhone vẫn chưa được công bố.",
        "Vì vậy bài nói có sức nặng đặc biệt: nó vừa là lời nhắn cho sinh viên tốt nghiệp, vừa là bản tóm lược triết lý sống của ông."
      ]
    },
    "contentChecksum": "sha256:1afda9d789dd93c84a5e7d2ca73befc454f777935aad01051e4187e0578adedb",
    "contentVersion": 1,
    "publicationMode": "summary",
    "images": [],
    "audio": []
  },
  {
    "slug": "tim-urban-inside-the-mind-of-a-master-procrastinator",
    "title": "Bên trong tâm trí của một bậc thầy trì hoãn",
    "description": "Trì hoãn không chỉ là lười; đó là một hệ thống tâm lý nơi phần thích dễ-vui chiếm tay lái, còn phần lý trí chỉ lấy lại quyền khi hoảng loạn xuất hiện.",
    "author": "Tim Urban",
    "source": "TED",
    "sourceUrl": "https://www.ted.com/talks/tim_urban_inside_the_mind_of_a_master_procrastinator",
    "sourcePublishedAt": null,
    "translator": null,
    "editor": null,
    "translatedAt": null,
    "lastReviewedAt": "2026-07-10",
    "rightsStatus": "source-link-only",
    "minutes": 14,
    "topics": [
      "cam-xuc",
      "hanh-phuc",
      "noi-tam"
    ],
    "intent": "clarity",
    "durationBand": "10-20",
    "readingPath": "/library/read/tim-urban-inside-the-mind-of-a-master-procrastinator",
    "coreIdea": "Trì hoãn không chỉ là lười; đó là một hệ thống tâm lý nơi phần thích dễ-vui chiếm tay lái, còn phần lý trí chỉ lấy lại quyền khi hoảng loạn xuất hiện.",
    "whyRead": "Bài này giúp người đọc nhìn sự trì hoãn bằng một mô hình dễ nhớ, đủ hài hước để không phòng thủ nhưng đủ sắc để nhận ra mình đang né điều gì.",
    "reflection": "Mình đang trì hoãn điều gì không có deadline nên không ai đánh thức Quái Vật Hoảng Loạn giúp mình?",
    "authorProfile": {
      "title": "Tim Urban là ai?",
      "summary": "Tim Urban là tác giả, blogger và illustrator người Mỹ, đồng sáng lập Wait But Why, nổi tiếng với các bài viết dài dùng hình vẽ đơn giản để giải thích những vấn đề lớn của đời sống.",
      "bullets": [
        "Wait But Why trở thành một trong những blog long-form có ảnh hưởng lớn nhờ cách kết hợp hài hước, sơ đồ trực quan và phân tích sâu.",
        "Bài TED 2016 của Urban về trì hoãn là một trong những TED Talk được xem nhiều nhất.",
        "Các mô hình như Instant Gratification Monkey, Panic Monster và Life Calendar giúp người đọc gọi tên những cơ chế tâm lý rất quen mà trước đó khó nắm bắt."
      ]
    },
    "contentContext": {
      "title": "Bài nói này ra đời trong bối cảnh nào?",
      "summary": "Bài nói được trình bày tại TED2016, dựa trên bài viết nổi tiếng của Tim Urban trên Wait But Why về vì sao người trì hoãn trì hoãn.",
      "bullets": [
        "Urban dùng chính câu chuyện luận văn đại học và quá trình chuẩn bị TED Talk để biến sự trì hoãn thành một mô hình dễ nhớ.",
        "Bài nói quan trọng vì nó chuyển chủ đề từ deadline ngắn hạn sang những việc lớn không có deadline: sức khỏe, quan hệ, nghệ thuật, sự nghiệp và đời sống chưa bắt đầu.",
        "Với thư viện này, bài giúp người đọc rèn năng lực tự quan sát thay vì chỉ tự trách."
      ]
    },
    "contentChecksum": "sha256:ba4b45c5df13f808e7edae0f5e433ee9a30abb0288502dc6f19a13ee3a4a74e5",
    "contentVersion": 1,
    "publicationMode": "summary",
    "images": [],
    "audio": []
  }
]
