import type { ChallengeDay } from './model'

export type LearningResource = Readonly<{
  id: string
  title: string
  type: 'Bản mẫu' | 'Ví dụ hoàn chỉnh' | 'Bảng kiểm' | 'Thẻ câu lệnh AI' | 'Gỡ vướng'
  description: string
  content: string
}>

const resources = (day: ChallengeDay, items: readonly Omit<LearningResource, 'id'>[]): readonly LearningResource[] =>
  items.map((item, index) => ({ ...item, id: `day-${day}-resource-${index + 1}` }))

export const DAY_RESOURCES: Record<ChallengeDay, readonly LearningResource[]> = {
  1: resources(1, [
    { type: 'Bản mẫu', title: 'Bản mô tả workflow trống', description: 'Chín câu hỏi để khóa phạm vi trước khi chọn công cụ.', content: 'Tên workflow: …\nCông việc lặp lại: …\nĐiểm kích hoạt: …\nĐầu vào hiện có: …\nĐầu ra cuối: …\nNgười dùng đầu ra: …\nVướng mắc hiện tại: …\nPhạm vi bảy ngày: …\nKhông làm: …\nHãy trả lời bằng điều bạn đang biết; chưa cần bằng chứng khách hàng.' },
    { type: 'Ví dụ hoàn chỉnh', title: 'Ba workflow đủ hẹp', description: 'Ví dụ cho bài chuyên môn, video ngắn và thư gửi khách hàng.', content: 'Bài chuyên môn: từ một ghi chú chuyên môn thành bài 700 chữ có một hành động. Video: từ một câu hỏi thường gặp thành kịch bản 60 giây đã duyệt. Thư: từ ghi chú cuộc họp thành thư cập nhật có quyết định và bước tiếp theo. Cả ba đều có điểm đầu, điểm cuối và người dùng rõ.' },
    { type: 'Bảng kiểm', title: 'Nhiệm vụ, câu lệnh, workflow hay tự động hóa?', description: 'Phân biệt bốn lớp thường bị trộn lẫn.', content: 'Nhiệm vụ là một việc cần làm. Câu lệnh là hướng dẫn cho AI trong một bước. Workflow là chuỗi chuyển đổi, quyết định và cổng chất lượng. Tự động hóa là cách công cụ tự chạy một phần workflow. Bạn đang thiết kế workflow; chưa cần chọn tự động hóa.' },
    { type: 'Gỡ vướng', title: 'Cách thu hẹp một ý quá rộng', description: 'Bốn câu hỏi khi bạn muốn “làm content tốt hơn”.', content: 'Hãy hỏi: một loại đầu ra nào xuất hiện lặp lại; sự kiện nào bắt đầu việc này; ai dùng đầu ra; trong bảy ngày bạn có thể chạy với đầu vào nào? Nếu vẫn có nhiều đáp án, chọn loại đầu ra bạn đã có dữ liệu gần nhất và ghi các loại còn lại vào mục Không làm.' },
  ]),
  2: resources(2, [
    { type: 'Bản mẫu', title: 'Hồ sơ bối cảnh trống', description: 'Tách dữ liệu ổn định, nhận định và khoảng trống.', content: 'Doanh nghiệp/dự án: …\nChuyên môn/offer: …\nNgười nhận: …\nĐiều đã biết: …\nNhận định hiện tại: …\nGiọng điệu: …\nPhải làm: …\nKhông được làm: …\nTài liệu tham chiếu: …\nKhoảng trống cần bổ sung: …\nKhông nhập bí mật, dữ liệu định danh hoặc thông tin bạn không có quyền dùng.' },
    { type: 'Ví dụ hoàn chỉnh', title: 'Hồ sơ bối cảnh Conan School', description: 'Một bản ngắn đủ để thiết kế bài học.', content: 'Conan School dành cho người xây lần đầu, giúp họ xây doanh nghiệp đầu tiên trong kỷ nguyên AI bằng cách tạo sản phẩm thật. Người đọc cần ngôn ngữ rõ, thực tế, không dạy đời. Nội dung phải dẫn tới hành động và không được bịa thành tích, doanh thu, khách hàng, lời chứng thực hay kết quả.' },
    { type: 'Bảng kiểm', title: 'Quyền riêng tư trước khi đưa dữ liệu vào AI', description: 'Loại bỏ chi tiết không cần thiết.', content: 'Trước khi sao chép, hãy bỏ tên, số điện thoại, thư điện tử, dữ liệu tài chính, bí mật kinh doanh và thông tin hợp đồng nếu workflow không cần chúng. Dùng vai trò hoặc mô tả tổng quát thay danh tính. Nếu không chắc mình có quyền sử dụng, hãy tóm tắt ở mức không thể nhận diện.' },
    { type: 'Thẻ câu lệnh AI', title: 'AI phỏng vấn bối cảnh', description: 'Dùng AI để lấy kiến thức đang ở trong đầu bạn.', content: 'Hãy hỏi tôi từng câu về doanh nghiệp, chuyên môn, người nhận, điều đã biết, nhận định, giọng điệu và giới hạn. Mỗi lượt chỉ hỏi một câu. Khi tóm tắt, giữ nguyên mức chắc chắn của tôi, đánh dấu khoảng trống và tuyệt đối không thêm thành tích, khách hàng, doanh thu hoặc bằng chứng chưa được cung cấp.' },
  ]),
  3: resources(3, [
    { type: 'Bản mẫu', title: 'Hợp đồng đầu ra trống', description: 'Tám trường để định nghĩa đích đến.', content: 'Người dùng đầu ra: …\nMục đích: …\nĐịnh dạng: …\nCấu trúc: …\nPhải có: …\nPhải tránh: …\nTiêu chí chất lượng có thể quan sát: …\nPhản ví dụ: …\nHãy viết tiêu chí như câu hỏi có thể trả lời có/không thay vì dùng tính từ chung chung.' },
    { type: 'Ví dụ hoàn chỉnh', title: 'Hợp đồng cho bài học công khai', description: 'Mẫu Conan School với ranh giới rõ.', content: 'Người dùng là người mới xây doanh nghiệp. Mục đích là hiểu một concept và tạo một sản phẩm nhỏ. Bài có bài toán, ba ý lý thuyết, hiểu lầm, ví dụ, hành động và tự kiểm. Phải tránh tuyên bố thiếu căn cứ. Đạt khi người mới giải thích lại được và hoàn thành sản phẩm không cần người hướng dẫn.' },
    { type: 'Bảng kiểm', title: 'Từ mơ hồ thành điều nhìn thấy', description: 'Dịch gu thành tiêu chí.', content: '“Rõ ràng” → mỗi phần một ý và có ví dụ. “Có chiều sâu” → giải thích nguyên nhân, ranh giới và đánh đổi. “Thực tế” → có hành động cùng sản phẩm đầu ra. “Đúng giọng” → có từ phải dùng, từ tránh và một đoạn mẫu. “Chuyên nghiệp” → cấu trúc nhất quán, không lỗi và không tuyên bố quá mức.' },
    { type: 'Gỡ vướng', title: 'Khi các tiêu chí mâu thuẫn', description: 'Ưu tiên theo mục đích sử dụng.', content: 'Nếu bạn vừa muốn rất ngắn vừa muốn giải thích đầy đủ, hãy quay lại mục đích và người dùng. Chia tiêu chí thành bắt buộc và ưu tiên. Giữ ba đến năm điều quyết định đầu ra có dùng được hay không; phần còn lại là điểm cộng, không phải cổng chặn workflow.' },
  ]),
  4: resources(4, [
    { type: 'Bản mẫu', title: 'Thẻ một bước workflow', description: 'Khối cơ bản của bản đồ.', content: 'Tên bước: …\nĐầu vào nhận được: …\nChuyển đổi phải thực hiện: …\nĐầu ra bàn giao: …\nQuyết định của con người: … hoặc “Không có”.\nCổng chất lượng: … hoặc để trống nếu chưa cần.\nMột bước tốt làm thay đổi trạng thái của công việc và để lại đầu ra có thể kiểm tra.' },
    { type: 'Ví dụ hoàn chỉnh', title: 'Bản đồ tài sản học tập Conan', description: 'Sáu bước minh họa thiết kế ngược.', content: '1. Nhận khái niệm nguồn. 2. Chọn lời hứa học tập—con người duyệt. 3. Lập dàn ý khái niệm và ranh giới. 4. Tạo ví dụ cùng hành động. 5. Viết nháp tài sản. 6. Kiểm tra sự thật, giọng điệu và sản phẩm—chỉ bàn giao khi vượt cổng. Mỗi bước dùng đầu ra trước làm đầu vào sau.' },
    { type: 'Bảng kiểm', title: 'Bước chính hay nhiệm vụ nhỏ?', description: 'Tránh bản đồ quá vụn.', content: 'Giữ thành bước chính nếu công việc tạo một đầu ra mới, chứa một quyết định, cần một cổng hoặc có thể thất bại độc lập. Chỉ là nhiệm vụ nhỏ nếu đó là thao tác như mở tệp, sao chép, đổi tab hoặc định dạng phụ. Gom nhiệm vụ nhỏ vào hướng dẫn của bước thay vì đưa hết lên bản đồ.' },
    { type: 'Thẻ câu lệnh AI', title: 'Phản biện bản đồ workflow', description: 'Tìm khoảng trống mà không giao quyền thiết kế.', content: 'Hãy đọc 4–7 bước của tôi và lập bảng: bước, đầu vào thiếu, đầu ra mơ hồ, bàn giao bị đứt, quyết định còn ẩn và trạng thái mắc kẹt. Chỉ nêu câu hỏi chẩn đoán cùng rủi ro. Không tự thêm, xóa, đổi thứ tự hay chọn công cụ cho tới khi tôi trả lời.' },
  ]),
  5: resources(5, [
    { type: 'Bản mẫu', title: 'Thẻ hướng dẫn từng bước', description: 'Biến bản đồ thành chỉ dẫn chạy được.', content: 'Vai trò: con người/AI/phối hợp/công cụ. Mục đích: …\nHướng dẫn: …\nĐịnh dạng đầu ra: …\nTự kiểm: …\nBàn giao: …\nNếu là điểm quyết định, hãy ghi ai quyết định và workflow phải chờ tín hiệu nào trước khi tiếp tục.' },
    { type: 'Bảng kiểm', title: 'Ma trận phân vai người–AI', description: 'Chọn vai trò theo bản chất quyết định.', content: 'Giao AI khi cần phương án, tóm tắt, chuyển đổi, định dạng hoặc kiểm theo luật. Giữ con người khi cần mục tiêu, đánh đổi, sự thật, quyền riêng tư, gu hoặc duyệt cuối. Dùng phối hợp khi AI chuẩn bị phương án còn con người quyết định. Dùng công cụ cho thao tác xác định và ít phán đoán.' },
    { type: 'Ví dụ hoàn chỉnh', title: 'Một thẻ hướng dẫn đạt yêu cầu', description: 'Ví dụ cho bước tạo góc học tập.', content: 'Vai trò: phối hợp. Mục đích: tạo ba góc khác nhau cho cùng lời hứa học tập. AI dùng Hồ sơ bối cảnh và Hợp đồng đầu ra, trả bảng ba dòng gồm luận điểm, ví dụ, hành động. Tự kiểm: không thêm claim. Bàn giao toàn bảng. Con người chọn một góc và workflow phải chờ lựa chọn.' },
    { type: 'Gỡ vướng', title: 'Vì sao câu lệnh khổng lồ dễ vỡ', description: 'Cách tách mà không làm workflow rườm rà.', content: 'Nếu một câu lệnh vừa nhận dữ liệu, chọn góc, viết, tự duyệt và sửa, bạn không biết lỗi xuất hiện ở đâu. Hãy tách tại điểm đầu ra có thể đọc hoặc nơi con người cần quyết định. Mỗi thẻ hướng dẫn nhận đầu vào rõ, tạo một đầu ra rõ rồi bàn giao; không nhất thiết mỗi thẻ cần một công cụ riêng.' },
  ]),
  6: resources(6, [
    { type: 'Bản mẫu', title: 'Nhật ký chạy thử', description: 'Lưu đầu ra, lỗi và can thiệp của từng bước.', content: 'Đầu vào thử: …\nVới từng bước ghi: đầu ra, vấn đề, can thiệp của con người.\nĐầu ra cuối: …\nĐánh giá theo Hợp đồng đầu ra: …\nLoại lỗi chính: …\nLỗi lớn nhất: …\nThay đổi đã làm: …\nKết quả chạy lại: …\nKhông xóa dấu vết của lần chạy đầu.' },
    { type: 'Bảng kiểm', title: 'Bảy nhóm lỗi workflow', description: 'Sửa đúng lớp thay vì đổ lỗi chung cho AI.', content: 'Bối cảnh: thông tin ổn định sai hoặc thiếu. Đầu vào: dữ liệu lần chạy không đủ. Hướng dẫn: thao tác mơ hồ. Bàn giao: mất dữ liệu giữa bước. Vai trò: giao sai người. Cổng: lỗi vẫn được đi tiếp. Hợp đồng: đích mâu thuẫn hoặc không kiểm được.' },
    { type: 'Ví dụ hoàn chỉnh', title: 'Một bản ghi trước và sau', description: 'Mẫu thay đổi có thể truy vết.', content: 'Trước: bước tạo góc trả ba phương án gần giống nhau. Phân loại: lỗi hướng dẫn. Thay đổi: yêu cầu ba góc khác nhau về luận điểm và mức hành động. Chạy lại đúng bước bằng cùng đầu vào. Sau: ba góc phân biệt được; con người chọn một góc. Kết luận chỉ giới hạn ở thay đổi vừa thử.' },
    { type: 'Gỡ vướng', title: 'Khi workflow mắc kẹt giữa chừng', description: 'Phục hồi mà không làm lại tất cả.', content: 'Dừng ở bước đầu tiên không thể tạo đầu ra. Giữ nguyên mọi đầu ra trước đó. Ghi điều còn thiếu và phân loại lỗi. Bổ sung tối thiểu dữ liệu hoặc hướng dẫn cần thiết, chạy lại bước hỏng rồi các bước phụ thuộc. Nếu phải dùng hiểu biết ngầm, hãy ghi can thiệp đó vào workflow.' },
  ]),
  7: resources(7, [
    { type: 'Bản mẫu', title: 'Hướng dẫn chạy một trang', description: 'Đủ để bạn hoặc người khác bắt đầu lại.', content: 'Phiên bản: …\nMục đích: …\nChuẩn bị: …\nCách chạy: …\nĐiểm con người quyết định: …\nCổng chất lượng: …\nBa lỗi phổ biến và cách phục hồi: …\nKhi nào cần cập nhật: …\nLịch sử thay đổi: ngày, bước, lỗi, thay đổi, kết quả chạy lại.' },
    { type: 'Bản mẫu', title: 'Bản thiết kế chuyển giao', description: 'Chứng minh bạn học được phương pháp chứ không chỉ chép mẫu.', content: 'Tên workflow mới: …\nKết quả cần tạo: …\nBối cảnh ổn định: …\nHợp đồng đầu ra: …\nCác bước chính: …\nĐiểm con người quyết định: …\nKế hoạch chạy thử: …\nHãy chọn một công việc khác content, ví dụ xử lý biên bản họp, chuẩn bị đề xuất hoặc tiếp nhận yêu cầu.' },
    { type: 'Bảng kiểm', title: 'Bàn giao và quản lý phiên bản', description: 'Đóng gói mà không làm tài liệu nặng nề.', content: 'Người nhận biết chuẩn bị gì, bắt đầu ở đâu, dùng tệp nào, dừng ở quyết định nào và đánh giá đầu ra ra sao. Mỗi lần sửa tăng phiên bản nhỏ, ghi nguyên nhân và kết quả chạy lại. Không xóa phiên bản từng dùng; không tự động hóa bước chưa ổn định.' },
    { type: 'Gỡ vướng', title: 'Kế hoạch 14 ngày sau thử thách', description: 'Tiếp tục bằng hai lần chạy có chủ đích.', content: 'Ngày 1–3 chọn đầu vào mới và chạy lần hai. Ngày 4 ghi lỗi lớn nhất và sửa một điểm. Ngày 5–7 chạy lại phần ảnh hưởng. Ngày 8–10 đưa workflow cho một người khác đọc. Ngày 11 sửa chỗ bàn giao. Ngày 12–14 chạy lần ba, cập nhật phiên bản và lưu cả ba nhật ký.' },
  ]),
}
